---
Name: codebasehq
---
SupportAPI:
  api_endpoint: '' #full url excl. project e.g. 'http://api3.codebasehq.com'
  project: '' #slug of the project
  web_endpoint: '' #full url excl. project e.g. 'http://yourdomain.codebasehq.com'
  auth:
    username: 'your/username' # username see Settings -> My Profile -> API Credentials
    token: 'key-here' # Settings -> My Profile -> API Credentials